headless-test:
	@nvim                \
	--headless           \
	--noplugin           \
	--clean              \
	-u tests/minimal.vim \
	-c "PlenaryBustedDirectory tests { minimal_init = 'tests/minimal.vim' }"

