#!/bin/sh

set -e
set -u

set -o errexit

git -c color.ui=always log \
	--all                   \
	--graph                 \
	--decorate              \
	--abbrev-commit         \
	--date=relative         \
   --pretty=tformat:'%C(red)%h%C(reset)}%C(dim yellow)(%ar)%C(reset)}—}%C(bold cyan)%an%C(reset):}%C(white)%s%C(reset) %C(dim white) %C(bold yellow)%d%C(reset)' \
| column -s '}' -t         \
| ${PAGER}
