local pipe = require('f.function.pipe')

describe('function', function()
	describe('pipe()', function()
		local e = function(n) return n + 1 end
		local g = function(n) return n * 2 end

		it('should return the given parameter', function() assert.same(2, pipe(2)) end)

		it('should pipe  1 function',  function() assert.same(3,    pipe(2, e)) end)
		it('should pipe  2 functions', function() assert.same(6,    pipe(2, e, g)) end)
		it('should pipe  3 functions', function() assert.same(7,    pipe(2, e, g, e)) end)
		it('should pipe  4 functions', function() assert.same(14,   pipe(2, e, g, e, g)) end)
		it('should pipe  5 functions', function() assert.same(15,   pipe(2, e, g, e, g, e)) end)
		it('should pipe  6 functions', function() assert.same(30,   pipe(2, e, g, e, g, e, g)) end)
		it('should pipe  7 functions', function() assert.same(31,   pipe(2, e, g, e, g, e, g, e)) end)
		it('should pipe  8 functions', function() assert.same(62,   pipe(2, e, g, e, g, e, g, e, g)) end)
		it('should pipe  9 functions', function() assert.same(63,   pipe(2, e, g, e, g, e, g, e, g, e)) end)
		it('should pipe 10 functions', function() assert.same(126,  pipe(2, e, g, e, g, e, g, e, g, e, g)) end)
		it('should pipe 11 functions', function() assert.same(127,  pipe(2, e, g, e, g, e, g, e, g, e, g, e)) end)
		it('should pipe 12 functions', function() assert.same(254,  pipe(2, e, g, e, g, e, g, e, g, e, g, e, g)) end)
		it('should pipe 13 functions', function() assert.same(255,  pipe(2, e, g, e, g, e, g, e, g, e, g, e, g, e)) end)
		it('should pipe 14 functions', function() assert.same(510,  pipe(2, e, g, e, g, e, g, e, g, e, g, e, g, e, g)) end)
		it('should pipe 15 functions', function() assert.same(511,  pipe(2, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e)) end)
		it('should pipe 16 functions', function() assert.same(1022, pipe(2, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g)) end)
		it('should pipe 17 functions', function() assert.same(1023, pipe(2, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e)) end)
		it('should pipe 18 functions', function() assert.same(2046, pipe(2, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g)) end)
		it('should pipe 19 functions', function() assert.same(2047, pipe(2, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e)) end)
		it('should pipe 20 functions', function() assert.same(4094, pipe(2, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g)) end)
		it('should pipe 21 functions', function() assert.same(4095, pipe(2, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e, g, e)) end)
	end)
end)
