name: Test suite

on:
  - push
  - pull_request

jobs:
  test:
    name: Unit tests

    strategy:
      fail-fast: true
      matrix:
        system:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        version:
          - stable
          - nightly

    runs-on: ${{ matrix.system }}

    steps:
      # —— Github Actions setup —————————————————————————————————————————————

      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      # —— Neovim setup —————————————————————————————————————————————————————

      # https://github.com/rhysd/action-setup-vim (community)
      - name: Neovim setup
        uses: rhysd/action-setup-vim@v1
        with:
          neovim:  true
          version: ${{ matrix.version }}

      # —— Plenary setup ————————————————————————————————————————————————————

      - name: Plenary setup
        run: |
          git clone https://github.com/nvim-lua/plenary.nvim plenary

      # —— Unit tests ———————————————————————————————————————————————————————

      - name: Unit tests
        run: make headless-test
