;;;; init.el --- -*- lexical-binding: t -*-

(provide 'init)

;;;; -- LEXICAL BINDING --------------------------------------------------------

;;   until  emacs  24.1 (june  2012),  elisp  only had  dynamically  scoped
;;   variables, a feature, mostly by accident, common to old lisp dialects.
;;   while dynamic scope has some selective uses, it’s widely regarded as a
;;   mistake for  local variables,  and virtually  no other  languages have
;;   adopted it.

;;   → (https://nullprogram.com/blog/2016/12/22/)

;;;; -- LOAD PATH --------------------------------------------------------------

;;; user configuration path

(defconst config-user-dir
  (cond ((boundp           'user-emacs-directory) user-emacs-directory)
	((boundp           'user-init-directory)  user-init-directory)
	((file-directory-p "~/.config/emacs/")    "~/.config/emacs/")
	((file-directory-p "~/.emacs.d/")         "~/.emacs.d/")

	(t "~/.config/emacs/"))
  "Contains the user configuration directory")

;;; add given folder to load path

(defun add-to-load-path (folder)

  "Add `FOLDER' and its subdirectories to `load-path'."

  (let ((default-directory folder))
    (unless (member folder load-path)
      (add-to-list 'load-path folder))
    (normal-top-level-add-subdirs-to-load-path)))


;;;; -- INITIAL SETUP ----------------------------------------------------------

;; checkout -> https://github.com/YaronWittenstein/dotemacs
;; also     -> https://github.com/MatthewZMD/.emacs.d#org525adf2
;; and      -> https://github.com/noctuid/evil-guide

;; update load path with subfolder containing include files
(add-to-load-path      (expand-file-name "lisp" config-user-dir))
;; set the package directory
(setq package-user-dir (expand-file-name "pack" config-user-dir))

;;;; -- LOADING CONFIGURATION --------------------------------------------------

(require 'init-constants)
(require 'init-behavior)
(require 'init-encoding)
(require 'init-ux)
(require 'init-packages)


;;;; -- LOADING PACKAGES -------------------------------------------------------

(require 'package-gruvbox)
(require 'package-evil)
(require 'package-helm)
(require 'package-pinentry)
(require 'package-magit)


;;;; -- AUTOGENERATED CUSTOM CONFIGURATION -------------------------------------

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(pinentry evil-magit magit bash-completion helm-company helm-posframe powershell helm-lsp lsp-p4 lsp-ui company-lsp memory-usage web-mode php-mode gruvbox-theme telephone-line lsp-mode evil company helm)))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(setq x-alt-keysym 'meta)

(add-to-list 'default-frame-alist '(font . "Dyosevka-14:weight=demibold"))
(set-face-attribute 'default t
		    :family "Dyosevka"
		    :foundry "Dyosevka"
		    ;; :height "150"
		    :weight 'bold
		    :width 'normal)
