# ---------------------------------------------------------------------------- #
#               _____                                _                         #
#              (____ \                              | |                        #
#               _   \ \ _   _  ___   ___  ____ _   _| |  _ ____                #
#              | |   | | | | |/ _ \ /___)/ _  ) | | | | / ) _  |               #
#              | |__/ /| |_| | |_| |___ ( (/ / \ V /| |< ( ( | |               #
#              |_____/  \__  |\___/(___/ \____) \_/ |_| \_)_||_|               #
#                      (____/                                                  #
#                                                                              #
#                                                                              #
#      configuration for the dyosevka font, built using be5invis/iosevka.      #
#                                                                              #
# ---------------------------------------------------------------------------- #

[buildPlans.Dyosevka]
family   = 'Dyosevka'
spacing  = 'fixed'
serifs   = 'sans'
no-cv-ss = false
no-ligation = true

# ---------------------------------------------------------------------------- #
# Variant overrides

[buildPlans.Dyosevka.variants.design]
capital-a = 'curly-serifless'
capital-g = 'toothless-corner-serifless-hooked'
capital-i = 'serifed'
capital-k = 'curly-serifless'
capital-n = 'standard'
capital-p = 'closed'
capital-q = 'curly-tailed'
capital-r = 'curly'
capital-s = 'serifless'
capital-v = 'curly'
capital-w = 'curly'
capital-x = 'curly-serifless'
capital-y = 'curly-serifless'
capital-z = 'curly-serifed-with-crossbar'
a = 'single-storey-serifless'
b = 'toothless-rounded'
d = 'toothless-corner-serifless'
e = 'rounded'
f = 'flat-hook-tailed'
g = 'double-storey-open'
i = 'tailed'
j = 'serifless'
k = 'curly-serifless'
l = 'tailed'
m = 'earless-corner-double-arch-short-leg'
n = 'earless-corner-straight'
p = 'earless-corner'
q = 'earless-corner'
r = 'earless-rounded'
t = 'standard'
u = 'toothless-rounded'
v = 'curly'
w = 'curly'
x = 'curly-serifless'
y = 'cursive'
z = 'curly-serifless'

ampersand      = 'et-toothed'
asterisk       = 'turn-hex-low'
at             = 'short'
bar            = 'natural-slope'
brace          = 'curly'
caret          = 'low'
dollar         = 'open-cap'
lig-ltgteq     = 'slanted'
lower-alpha    = 'crossing'
lower-lambda   = 'curly'
number-sign    = 'slanted-open'
paren          = 'large-contour'
question       = 'corner-flat-hooked'
turn-v         = 'curly'

zero  = 'dotted'
two   = 'curly-neck'
five  = 'oblique-upper-left-bar'
six   = 'open-contour'
seven = 'curly-serifed'
eight = 'crossing-asymmetric'
nine  = 'open-contour'

punctuation-dot = 'round'

# ---------------------------------------------------------------------------- #
# Metric overrides

[buildPlans.Dyosevka.metric-override]
# leading = 1250
