# ---------------------------------------------------------------------------- #
#               _____                                _                         #
#              (____ \                              | |                        #
#               _   \ \ _   _  ___   ___  ____ _   _| |  _ ____                #
#              | |   | | | | |/ _ \ /___)/ _  ) | | | | / ) _  |               #
#              | |__/ /| |_| | |_| |___ ( (/ / \ V /| |< ( ( | |               #
#              |_____/  \__  |\___/(___/ \____) \_/ |_| \_)_||_|               #
#                      (____/                                                  #
#                                                                              #
#                                                                              #
#      configuration for the dyosevka font, built using be5invis/iosevka.      #
#                                                                              #
# ---------------------------------------------------------------------------- #

# Built with be5invis/iosevka version 26.3.3

[buildPlans.Dyosevka]
family   = "Dyosevka"
spacing  = "term"
serifs   = "sans"
no-cv-ss = false
no-ligation = true
export-glyph-names = false

# ---------------------------------------------------------------------------- #
# Variant overrides

[buildPlans.Dyosevka.variants.design]
capital-a = "curly-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-i = "serifed"
capital-k = "curly-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "curly-tailed"
capital-r = "curly-serifless"
capital-s = "serifless"
capital-v = "curly-serifless"
capital-w = "curly-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifed-with-crossbar"
a = "single-storey-serifed"
b = "toothless-rounded-serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey-open"
i = "tailed"
j = "serifless"
k = "curly-serifless"
l = "tailed"
m = "earless-corner-double-arch-short-leg-serifless"
n = "earless-corner-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "curly-serifless"
w = "curly-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "curly-serifless"

ampersand      = "et-toothed"
asterisk       = "turn-hex-low"
at             = "compact"
bar            = "natural-slope"
brace          = "curly"
caret          = "low"
dollar         = "open-cap"
lig-ltgteq     = "slanted"
lower-alpha    = "crossing"
capital-lambda = "curly-serifless"
lower-lambda   = "curly"
number-sign    = "slanted-open"
paren          = "large-contour"
question       = "corner-flat-hooked"

zero  = "dotted"
two   = "curly-neck"
five  = "oblique-upper-left-bar"
six   = "open-contour"
seven = "curly-serifed"
eight = "crossing-asymmetric"
nine  = "open-contour"

punctuation-dot = "round"

# ---------------------------------------------------------------------------- #
# Metric overrides

[buildPlans.Dyosevka.metric-override]
# leading = 1250
