((enum_variant)                     @swappable)
((field_declaration)                @swappable)
((function_item)                    @swappable)
((match_arm)                        @swappable)
((meta_item)                        @swappable)
(arguments                      (_) @swappable)
(array_expression               (_) @swappable)
(field_initializer_list         (_) @swappable)
(ordered_field_declaration_list (_) @swappable)
(parameters                     (_) @swappable)
(use_list                       (_) @swappable)
